//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThemeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public int OrderId { get; set; }
        public Nullable<int> ProId { get; set; }
        public string UserId { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Total { get; set; }
        public string PayMethod { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
